server:
  port: 8088

#logging:
#  level:
#    org.springframework: DEBUG

spring:
  jpa:
    show-sql: true
    # 쿼리 log 파일에 출력
  messages:
    basename: messages
    # 다국어 사용할 파일 이름: messages
  security:
    user:
      name: username # id
      password: passw0rd # password

management:
  endpoints:
    web:
      exposure:
        include: "*"
        # actuator, 더 다양한 정보 볼 수 있음
